### ISSUE TITLE
For individual reactions.txt outputs for each sample, sort by reaction name in output file

### ISSUE THREAD

**Issue by AlexKhodaverdian** [YosefLab/Compass#10]
For individual reactions.txt outputs for each sample, sort by reaction name in output file. My guess is the output is by reading key values from a dictionary, which is unordered and random at times.

**Comment by solocell** [comment]
Hi buddy,

I tried to run compass on our computation node. However, it turns out, 
KeyError: 'no_metabolites' 

Could  you please look into the script?

[pi@node]$ compass --data test.txt --num-processes 10 --num-threads 10 --calc-metabolites
Reaction Penalties already evaluated
Resuming execution from previous run...
Processing 5 samples using 20 processes
Progress bar will update once the first sample is finished
  0%|                                                                                                                | 0/5 [00:00<?, ?it/s]Collecting results from: /data1/singlecell/_tmp
Writing output to: /data1/singlecell
Traceback (most recent call last):
  File "/usr/bin/compass", line 8, in <module>
    sys.exit(entry())
  File "/src/lib/python3.6/site-packages/compass_sc-0.9.5-py3.6-linux-x86_64.egg/compass/main.py", line 263, in entry
    runCompassParallel(args)
  File "/src/sc-tutorial/lib/python3.6/site-packages/compass_sc-0.9.5-py3.6-linux-x86_64.egg/compass/main.py", line 303, in runCompassParallel
    args['output_dir'], args)
  File "/src/lib/python3.6/site-packages/compass_sc-0.9.5-py3.6-linux-x86_64.egg/compass/main.py", line 437, in collectCompassResults
    if not args['no_metabolites']: 
	KeyError: 'no_metabolites'

**Comment by DPLemonade** [comment]
Marking as resolved
