### ISSUE TITLE
Buggs in the latest version when using example data

### ISSUE THREAD

**Issue by Hrovatin** [YosefLab/Compass#30]
I installed compass today.
I had a few issues running compas with example data:
```
(compass) [karin.hrovatin@icb-lisa mtx_format]$ compass --data-mtx matrix.mtx genes.tsv barcodes.tsv --output-dir $WS/data/p$ncreas/scRNA/compass_try/ --model RECON2.2 --calc-metabolites --lambda 0.1 --num-processes 12 --num-threads 4 --microcluster$size 4
Partitioning dataset into 4 microclusters
Traceback (most recent call last):
  File "/home/icb/karin.hrovatin/miniconda3/envs/compass/bin/compass", line 8, in <module>                                  
    sys.exit(entry())
  File "/home/icb/karin.hrovatin/miniconda3/envs/compass/lib/python3.8/site-packages/compass/main.py", line 358, in entry
    pools = microcluster(data, cellsPerPartition = args['microcluster_size'],
  File "/home/icb/karin.hrovatin/miniconda3/envs/compass/lib/python3.8/site-packages/compass/compass/microclustering.py", lin
e 38, in microcluster
    pca_expression = model.fit_transform(log_expression_filtered.T).T
  File "/home/icb/karin.hrovatin/.local/lib/python3.8/site-packages/sklearn/decomposition/_pca.py", line 376, in fit_transfor
m
    U, S, Vt = self._fit(X)
  File "/home/icb/karin.hrovatin/.local/lib/python3.8/site-packages/sklearn/decomposition/_pca.py", line 397, in _fit
    X = self._validate_data(X, dtype=[np.float64, np.float32],
  File "/home/icb/karin.hrovatin/.local/lib/python3.8/site-packages/sklearn/base.py", line 421, in _validate_data
    X = check_array(X, **check_params)
  File "/home/icb/karin.hrovatin/.local/lib/python3.8/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/home/icb/karin.hrovatin/.local/lib/python3.8/site-packages/sklearn/utils/validation.py", line 593, in check_array
    array = _ensure_sparse_format(array, accept_sparse=accept_sparse,
  File "/home/icb/karin.hrovatin/.local/lib/python3.8/site-packages/sklearn/utils/validation.py", line 360, in _ensure_sparse
_format
    raise TypeError('A sparse matrix was passed, but dense '
TypeError: A sparse matrix was passed, but dense data is required. Use X.toarray() to convert to a dense numpy array.
```
Resolved by model.fit_transform(log_expression_filtered.values.T).T

```
s/bin/compass", line 33, in <module>                                 
    sys.exit(load_entry_point('compass-sc', 'console_scripts', 'compass')())                                                
  File "/home/icb/karin.hrovatin/miniconda3/envs/compass/lib/python3.8/site-packages/Compass/compass/main.py", line 440, in entry
    penalties = eval_reaction_penalties(args['data'], args['model'],                                                        
  File "/home/icb/karin.hrovatin/miniconda3/envs/compass/lib/python3.8/site-packages/Compass/compass/compass/penalties.py", line 94, in eval_reaction_penalties
    reaction_penalties = eval_reaction_penalties_shared(
  File "/home/icb/karin.hrovatin/miniconda3/envs/compass/lib/python3.8/site-packages/Compass/compass/compass/penalties.py", line 178, in eval_reaction_penalties_shared
    model = PCA(n_components=min(log_expression_filtered.shape[0], log_expression_filtered.shape[1], 20),                   
NameError: name 'log_expression_filtered' is not defined
```
resolved by PCA(n_components=min(log_expression.shape[0], log_expression.shape[1], 20),

**Comment by schel337** [comment]
Thanks for reporting this bug, the issue with sparse matrix types should now be resolved. The second bug should have been fixed a couple of days ago, but let us know if you run into any other issues.

If you installed Compass with pip, you can just run "pip install --upgrade git+https://github.com/yoseflab/Compass.git" to update it.
