### ISSUE TITLE
"Index length mismatch" OR "Can only use .str accessor with string values!"

### ISSUE THREAD

**Issue by Roger-GOAT** [YosefLab/Compass#40]
Hi team, great interest in the wonderful software! 
When I run this in 10x folder
```
(compass) vip06@bio3:~/scdata/filter/day5$ compass --data-mtx matrix.mtx.gz features.tsv.gz barcodes.tsv.gz --num-processes 12 --specie mus_musculus
Evaluating Reaction Penalties...
Traceback (most recent call last):
  File "/home/data/vip06/miniconda3/envs/compass/bin/compass", line 8, in <module>
    sys.exit(entry())
  File "/home/data/vip06/miniconda3/envs/compass/lib/python3.8/site-packages/compass/main.py", line 546, in entry
    penalties = eval_reaction_penalties(args['data'], args['model'],
  File "/home/data/vip06/miniconda3/envs/compass/lib/python3.8/site-packages/compass/compass/penalties.py", line 59, in eval_reaction_penalties
    expression = utils.read_data(expression_file) #pd.read_csv(expression_file, sep='\t', index_col=0)
  File "/home/data/vip06/miniconda3/envs/compass/lib/python3.8/site-packages/compass/utils.py", line 55, in read_data
    return read_mtx(data[0], data[1], data[2])
  File "/home/data/vip06/miniconda3/envs/compass/lib/python3.8/site-packages/compass/utils.py", line 80, in read_mtx
    return pd.DataFrame.sparse.from_spmatrix(mtx, index=rows.to_numpy().ravel(), columns = columns)
  File "/home/data/vip06/miniconda3/envs/compass/lib/python3.8/site-packages/pandas/core/arrays/sparse/accessor.py", line 264, in from_spmatrix
    index, columns = cls._prep_index(data, index, columns)
  File "/home/data/vip06/miniconda3/envs/compass/lib/python3.8/site-packages/pandas/core/arrays/sparse/accessor.py", line 378, in _prep_index
    raise ValueError(f"Index length mismatch: {len(index)} vs. {N}")
ValueError: Index length mismatch: 93159 vs. 31053
```
OR if I get a .tsv first in R
```
> expression <- as.data.frame(GetAssayData(SeuratObject,slot = 'counts',assay = "RNA"))
> write_tsv(expression,file = 'result/expression.tsv',col_names = F/T(both had tried))
```
and in compass
```
(compass) vip06@bio3:~/result$ compass --data expression.tsv --num-processes 10 --species mus_musculus
Evaluating Reaction Penalties...
Traceback (most recent call last):
  File "/home/data/vip06/miniconda3/envs/compass/bin/compass", line 8, in <module>
    sys.exit(entry())
  File "/home/data/vip06/miniconda3/envs/compass/lib/python3.8/site-packages/compass/main.py", line 546, in entry
    penalties = eval_reaction_penalties(args['data'], args['model'],
  File "/home/data/vip06/miniconda3/envs/compass/lib/python3.8/site-packages/compass/compass/penalties.py", line 60, in eval_reaction_penalties
    expression.index = expression.index.str.upper()  # Gene names to upper
  File "/home/data/vip06/miniconda3/envs/compass/lib/python3.8/site-packages/pandas/core/accessor.py", line 181, in __get__
    accessor_obj = self._accessor(obj)
  File "/home/data/vip06/miniconda3/envs/compass/lib/python3.8/site-packages/pandas/core/strings/accessor.py", line 168, in __init__
    self._inferred_dtype = self._validate(data)
  File "/home/data/vip06/miniconda3/envs/compass/lib/python3.8/site-packages/pandas/core/strings/accessor.py", line 225, in _validate
    raise AttributeError("Can only use .str accessor with string values!")
AttributeError: Can only use .str accessor with string values!
(compass) vip06@bio3:~/result$ compass --data expression.tsv --num-processes 10 --species mus_musculus
Evaluating Reaction Penalties...
Traceback (most recent call last):
  File "/home/data/vip06/miniconda3/envs/compass/bin/compass", line 8, in <module>
    sys.exit(entry())
  File "/home/data/vip06/miniconda3/envs/compass/lib/python3.8/site-packages/compass/main.py", line 546, in entry
    penalties = eval_reaction_penalties(args['data'], args['model'],
  File "/home/data/vip06/miniconda3/envs/compass/lib/python3.8/site-packages/compass/compass/penalties.py", line 60, in eval_reaction_penalties
    expression.index = expression.index.str.upper()  # Gene names to upper
  File "/home/data/vip06/miniconda3/envs/compass/lib/python3.8/site-packages/pandas/core/accessor.py", line 181, in __get__
    accessor_obj = self._accessor(obj)
  File "/home/data/vip06/miniconda3/envs/compass/lib/python3.8/site-packages/pandas/core/strings/accessor.py", line 168, in __init__
    self._inferred_dtype = self._validate(data)
  File "/home/data/vip06/miniconda3/envs/compass/lib/python3.8/site-packages/pandas/core/strings/accessor.py", line 225, in _validate
    raise AttributeError("Can only use .str accessor with string values!")
AttributeError: Can only use .str accessor with string values!
```
Could you give me a hand? really like the software to explorer metabolic.

**Comment by schel337** [comment]
Hi, glad you like the software.

I think the change I pushed should fix the error with the tsv format by casting that column to a string, though having non-string gene names might indicate something is off with the input format (e.g. the rows of the tsv have numbers labelling each row rather than gene names).

For the mtx format issue I would suggest opening up the files with python in pandas using pandas.open_csv(features.tsv.gz, sep="\t", header=None) and confirming that the number of rows of the features.txt.gz is the same as the number of rows as matrix.mtx.gz. The error indicates that the list of features (presumed to be genes) is a different length than the matrix of gene expression.

**Comment by naveena-ujagar** [comment]
Hello!

I am experiencing something similar:
`PS C:\Users\sosha\Desktop\FilteredMatrixFiles\NP> compass --data-mtx matrix.mtx.gz features.tsv.gz barcodes.tsv.gz --num-processes 10 --species homo_sapiens
Cache for model and media already built
Evaluating Reaction Penalties...
Traceback (most recent call last):
  File "C:\Users\sosha\AppData\Local\Programs\Python\Python38\Scripts\compass-script.py", line 11, in <module>
    load_entry_point('compass-sc==0.9.10.2', 'console_scripts', 'compass')()
  File "C:\Users\sosha\AppData\Local\Programs\Python\Python38\lib\site-packages\compass\main.py", line 588, in entry
    penalties = eval_reaction_penalties(args['data'], args['model'],
  File "C:\Users\sosha\AppData\Local\Programs\Python\Python38\lib\site-packages\compass\compass\penalties.py", line 60, in eval_reaction_penalties
    expression = utils.read_data(expression_file) #pd.read_csv(expression_file, sep='\t', index_col=0)
  File "C:\Users\sosha\AppData\Local\Programs\Python\Python38\lib\site-packages\compass\utils.py", line 62, in read_data
    return read_mtx(data[0], data[1], data[2])
  File "C:\Users\sosha\AppData\Local\Programs\Python\Python38\lib\site-packages\compass\utils.py", line 121, in read_mtx
    return pd.DataFrame.sparse.from_spmatrix(mtx, index=rows.to_numpy().ravel(), columns = columns)
  File "C:\Users\sosha\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\arrays\sparse\accessor.py", line 275, in from_spmatrix
    index, columns = cls._prep_index(data, index, columns)
  File "C:\Users\sosha\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\arrays\sparse\accessor.py", line 395, in _prep_index
    raise ValueError(f"Index length mismatch: {len(index)} vs. {N}")
ValueError: Index length mismatch: 109803 vs. 36601
PS C:\Users\sosha\Desktop\FilteredMatrixFiles\NP>`

Some context 
`Compass version: 0.9.10.2
Git commit: Not in Git repo
Python Version:
3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)]
Python prefix: C:\Users\sosha\AppData\Local\Programs\Python\Python38
Numpy version: 1.24.2
Pandas version: 1.5.3
Supplied Arguments: 
   data: ['C:\\Users\\sosha\\Desktop\\FilteredMatrixFiles\\NP\\matrix.mtx.gz', 'C:\\Users\\sosha\\Desktop\\FilteredMatrixFiles\\NP\\features.tsv.gz', 'C:\\Users\\sosha\\Desktop\\FilteredMatrixFiles\\NP\\barcodes.tsv.gz']
   data_mtx: ['matrix.mtx.gz', 'features.tsv.gz', 'barcodes.tsv.gz']
   model: RECON2_mat
   species: homo_sapiens
   media: default-media
   output_dir: C:\Users\sosha\Desktop\FilteredMatrixFiles\NP
   temp_dir: C:\Users\sosha\Desktop\FilteredMatrixFiles\NP\_tmp
   torque_queue: None
   num_processes: 10
   lambda: 0
   single_sample: None
   transposed: False
   sample_range: None
   reaction_range: None
   metabolite_range: None
   generate_cache: False
   test_mode: False
   num_threads: 1
   and_function: mean
   select_reactions: None
   select_subsystems: None
   glucose: None
   collect: False
   config_file: None
   num_neighbors: 30
   symmetric_kernel: False
   input_weights: None
   penalty_diffusion: knn
   no_reactions: False
   calc_metabolites: False
   precache: False
   input_knn: None
   input_knn_distances: None
   output_knn: None
   latent_space: None
   only_penalties: None
   example_inputs: None
   microcluster_size: None
   microcluster_file: None
   microcluster_data_file: None
   anndata_output: False
   anndata_obs: None
   anndata_uns: None
   detailed_perf: False
   penalties_file: 
   lpmethod: 4
   advance: 2
   save_argmaxes: False
   isoform_summing: remove-summing
   list_genes: None
   list_reactions: None

COMPASS Started: 2023-04-18 16:51:30.902277
Cache for model and media already built
Evaluating Reaction Penalties...`

Not sure how to fix it with this being the first time I'm coding...

**Comment by Bisho2122** [comment]
I also got a similar error, but I think it expects 'features.tsv.gz' to only have 1 column. So I kept only the ensembl IDs and it worked.

**Comment by skoturan** [comment]
Hi, I have the same error- can you please help?

`Traceback (most recent call last):
  File "/rds/general/user/sk4914/home/anaconda3/envs/compass/bin/compass", line 8, in <module>
    sys.exit(entry())
  File "/rds/general/user/sk4914/home/anaconda3/envs/compass/lib/python3.8/site-packages/compass/main.py", line 588, in entry
    penalties = eval_reaction_penalties(args['data'], args['model'],
  File "/rds/general/user/sk4914/home/anaconda3/envs/compass/lib/python3.8/site-packages/compass/compass/penalties.py", line 60, in eval_reaction_penalties
    expression = utils.read_data(expression_file) #pd.read_csv(expression_file, sep='\t', index_col=0)
  File "/rds/general/user/sk4914/home/anaconda3/envs/compass/lib/python3.8/site-packages/compass/utils.py", line 62, in read_data
    return read_mtx(data[0], data[1], data[2])
  File "/rds/general/user/sk4914/home/anaconda3/envs/compass/lib/python3.8/site-packages/compass/utils.py", line 121, in read_mtx
    return pd.DataFrame.sparse.from_spmatrix(mtx, index=rows.to_numpy().ravel(), columns = columns)
  File "/rds/general/user/sk4914/home/anaconda3/envs/compass/lib/python3.8/site-packages/pandas/core/arrays/sparse/accessor.py", line 270, in from_spmatrix
    index, columns = cls._prep_index(data, index, columns)
  File "/rds/general/user/sk4914/home/anaconda3/envs/compass/lib/python3.8/site-packages/pandas/core/arrays/sparse/accessor.py", line 385, in _prep_index
    raise ValueError(f"Index length mismatch: {len(index)} vs. {N}")
ValueError: Index length mismatch: 113729 vs. 36601`


Did anyone solve this? I tried the suggestions discussed here and no luck. 
Would appreciate your thoughts!
Thanks
