### ISSUE TITLE
tsne_utils import error: try recompiling

### ISSUE THREAD

**Issue by Hrovatin** [YosefLab/Compass#48]
How can I solve the below error? I already had compass running in the same env, but now it stopped - no idea why.
```
Traceback (most recent call last):
  File "/home/icb/karin.hrovatin/miniconda3/envs/compass/bin/compass", line 33, in <module>
    sys.exit(load_entry_point('compass-sc', 'console_scripts', 'compass')())
  File "/home/icb/karin.hrovatin/miniconda3/envs/compass/bin/compass", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/icb/karin.hrovatin/miniconda3/envs/compass/lib/python3.8/importlib/metadata.py", line 75, in load
    module = import_module(match.group('module'))
  File "/home/icb/karin.hrovatin/miniconda3/envs/compass/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/icb/karin.hrovatin/miniconda3/envs/compass/lib/python3.8/site-packages/Compass/compass/main.py", line 28, in <module>
    from .compass.penalties import eval_reaction_penalties, compute_knn
  File "/home/icb/karin.hrovatin/miniconda3/envs/compass/lib/python3.8/site-packages/Compass/compass/compass/penalties.py", line 4, in <module>
    from .extensions import tsne_utils
  File "__init__.pxd", line 181, in init compass.compass.extensions.tsne_utils (compass/compass/extensions/tsne_utils.c:5875)
ValueError: numpy.ndarray has the wrong size, try recompiling. Expected 80, got 88

```

**Comment by schel337** [comment]
I have not run into this error and the tsne utils have been left as-is for a long time, so I would guess that this might be caused by changing/updating numpy as the tsne utils rely upon numpy's C code. I would suggest re-installing Compass to force the tsne utils to be linked correctly or installing Compass in the environment somewhere else and copying the tsne files over.

Does this happen when using the gaussian penalty diffusion or just when running Compass? I'm assuming it's the latter above.

If you are not using the gaussian penalty diffusion you could also remove the tsne extension and the calls that use it/import it in the penalties computation.

**Comment by Hrovatin** [comment]
I have tried reinstalling both numpy, Compass, and cython, but did not work. I solved it by making a new env and reinstalling all from scratch.
