### ISSUE TITLE
TypeError("cannot pickle 'SwigPyObject' object")

### ISSUE THREAD

**Issue by songtt135790** [YosefLab/Compass#60]
hello,

I am running compass with own expression data but  I get an error:

'```
Traceback (most recent call last):
  File "/data/nfs01/output/songtt/conda_pkg/bin/compass", line 8, in <module>
    sys.exit(entry())
  File "/data/nfs01/output/songtt/conda_pkg/lib/python3.8/site-packages/compass/main.py", line 572, in entry
    precacheCompass(args=args)
  File "/data/nfs01/output/songtt/conda_pkg/lib/python3.8/site-packages/compass/main.py", line 873, in precacheCompass
    for sub_cache in pool.imap_unordered(partial_map_fun, reaction_chunks):
  File "/data/nfs01/output/songtt/conda_pkg/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7fb3233cb6d0>'. Reason: 'TypeError("cannot pickle 'SwigPyObject' `object")'
````
and my code is
compass --data /data/nfs01/output/songtt/compass/LUSC_malignant_exp.tsv --num-processes 6 --species homo_sapiens --output-dir /data/nfs01/output/songtt/compass

I also using pandas.read_csv("LUSC_malignant_exp.tsv", sep="\t", index_col=0) to read the tsv file, that is OK

Do you know how to solve this ??

Thanks

**Comment by gherr-01** [comment]
Hallo,
same thing with me. Using my Mac and own expression data of 6 samples. Tsv file is ok. Compass seems to work when typing -h. Also tried older python versions or mtx file, always encountering the same error.
Would be great if you could help me as well :-)

Thanks!

**Comment by quangdang1998** [comment]
Hello, I have been getting the same issue with my own expression count matrix. The error shows up even when I try to run it on the test dataset, leading me to believe this is an installation issue. Did you figure out a way to troubleshoot?

**Comment by yi-jun1** [comment]
Having a same issue. It doesn't work even when I try to run with the example samples such as "expression.tsv".

**Comment by yi-jun1** [comment]
In my case, after creating a virtual environment to match the python version for Compass and CPLEX, the problem was solved. Hope this solution helps someone. To make a virtual environment, I used the following reference (https://medium.datadriveninvestor.com/how-to-install-and-manage-multiple-python-versions-on-linux-916990dabe4b). The user setting with and without "sudo su" will change your python version. So make sure that you are installing those programs within the same python version when installing.

**Comment by junjieahaha** [comment]
> In my case, after creating a virtual environment to match the python version for Compass and CPLEX, the problem was solved. Hope this solution helps someone. To make a virtual environment, I used the following reference (https://medium.datadriveninvestor.com/how-to-install-and-manage-multiple-python-versions-on-linux-916990dabe4b).
What's the python version  and packages version are you using ?

**Comment by junjieahaha** [comment]
@yi-jun1   What's the python version and packages version are you using ?

**Comment by sangderk** [comment]
I have the same error...with python 3.7.12.

**Comment by Pinuslin** [comment]
> I solved the problem by reinstalling cplex.
> 'conda install -c ibmdecisionoptimization cplex ' may cause the error.
> download the cplex installation package, in cplex/python/3.6/x86-64_linux , ’ python setup.py install ‘ successfully installed cplex. And the error disappears.

My cplex version is 20.1.0.0 and it don't have python3.6 package. I installed python3.7 version package and it didn't work.

**Comment by Xparx** [comment]
I have the same issue,

```
$ python --version
Python 3.10.6
$ pip list
Package         Version
--------------- --------
anndata         0.8.0
compass-sc      0.9.10.2
cplex           22.1.0.0
h5py            3.7.0
igraph          0.10.2
joblib          1.2.0
leidenalg       0.9.0
natsort         8.2.0
numpy           1.23.4
packaging       21.3
pandas          1.5.1
pip             22.1.2
pyparsing       3.0.9
python-dateutil 2.8.2
python-igraph   0.10.2
python-libsbml  5.19.7
pytz            2022.5
scikit-learn    1.1.3
scipy           1.9.3
six             1.16.0
texttable       1.6.4
threadpoolctl   3.1.0
tqdm            4.64.1
```
The issue arises already at the cache stage when running 
```
compass --precache --species homo_sapiens
```
All installed in a conda environment running 
`conda install -c ibmdecisionoptimization cplex`
then after error I did a `pip install cplex` but so far no luck.

**Comment by deto** [comment]
Generally this issue can occur when the cplex edition you have installed is just the community edition.  For the community edition, the problem size is limited and it won't run optimizations with the 1000s of reactions/metabolites involved in the human or mouse models.  

Instead, you should install the free for academic use edition (if you are at a university).  There used to be a link in the instructions for this (might still be there), but IBM also may have changed their website since then so you might have to do some searching.
