### ISSUE TITLE
TypeError("cannot pickle 'SwigPyObject' object")

### ISSUE THREAD

**Issue by garricklu** [YosefLab/Compass#64]
hello,

I am running compass with example inputs data but I get an error:

`Building up model cache
  0%|                                                                                                                                                 | 0/1022 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/data/vip49/miniconda3/envs/cnmf_env/bin/compass", line 33, in <module>
    sys.exit(load_entry_point('compass-sc==0.9.10.1', 'console_scripts', 'compass')())
  File "/home/data/vip49/miniconda3/envs/cnmf_env/lib/python3.7/site-packages/compass_sc-0.9.10.1-py3.7.egg/compass/main.py", line 572, in entry
    precacheCompass(args=args)
  File "/home/data/vip49/miniconda3/envs/cnmf_env/lib/python3.7/site-packages/compass_sc-0.9.10.1-py3.7.egg/compass/main.py", line 873, in precacheCompass
    for sub_cache in pool.imap_unordered(partial_map_fun, reaction_chunks):
  File "/home/data/vip49/miniconda3/envs/cnmf_env/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7f1aaae9cd30>'. Reason: 'TypeError("can't pickle SwigPyObject objects")'`

Here is my code:
`compass --data /home/vip49/20220318/expression.tsv --num-processes 10 --species homo_sapiens`

I get an error even i only want to build up the cache before running Compass:

`Traceback (most recent call last):
  File "/home/data/vip49/miniconda3/envs/cnmf_env/bin/compass", line 33, in <module>
    sys.exit(load_entry_point('compass-sc==0.9.10.1', 'console_scripts', 'compass')())
  File "/home/data/vip49/miniconda3/envs/cnmf_env/lib/python3.7/site-packages/compass_sc-0.9.10.1-py3.7.egg/compass/main.py", line 572, in entry
    precacheCompass(args=args)
  File "/home/data/vip49/miniconda3/envs/cnmf_env/lib/python3.7/site-packages/compass_sc-0.9.10.1-py3.7.egg/compass/main.py", line 873, in precacheCompass
    for sub_cache in pool.imap_unordered(partial_map_fun, reaction_chunks):
  File "/home/data/vip49/miniconda3/envs/cnmf_env/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7f3e40937dd8>'. Reason: 'TypeError("can't pickle SwigPyObject objects")'`

Do you know how to solve this ??

Thanks

**Comment by Roger-GOAT** [comment]
some issue, are u solve it？
