### ISSUE TITLE
running Compass from a Singularity image

### ISSUE THREAD

**Issue by hmassalha** [YosefLab/Compass#67]
Thanks for making this amazing tool. 
I am trying to run Compass from a Singularity image. While the task is running, I am getting the following error msg: 
```
 Traceback (most recent call last):
  File "/usr/local/bin/compass", line 8, in <module>
    sys.exit(entry())
  File "/usr/local/lib/python3.8/site-packages/compass/main.py", line 572, in entry
    precacheCompass(args=args)
  File "/usr/local/lib/python3.8/site-packages/compass/main.py", line 884, in precacheCompass
    cache.clear(model)
  File "/usr/local/lib/python3.8/site-packages/compass/compass/cache.py", line 85, in clear
    save(model, media)
  File "/usr/local/lib/python3.8/site-packages/compass/compass/cache.py", line 55, in save
    os.makedirs(cache_dir)
  File "/usr/local/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/usr/local/lib/python3.8/site-packages/compass/Resources/COMPASS/RECON2_mat/default-media'
```
I would assume this is because my image is not writable, I might be mistaken. Any suggestion how to overcome this issue? 

EDIT: I got the same error msg when running the test-data

Thanks, HM

**Comment by maflister** [comment]
We are seeing a similar error on the same file path when running compass natively (no Singularity). Although the error is "Permission denied" instead of "Read-only". Please advise.

**Comment by blakedewey** [comment]
We also are running this in Singularity, but this is a generic issue with any install where the Compass install directory is not writable by the user. This seems to stem from the "caching" that Compass does, which uses a subdirectory of the `RESOURCE_DIR` global. Perhaps this can be changed to use the `--temp-dir` as it's root directory?

**Comment by hmassalha** [comment]
it helps, thanks a lot, and sorry for the delay reply.
