### ISSUE TITLE
 Numeric entry is not a double precision number (NaN)

### ISSUE THREAD

**Issue by littleju777** [YosefLab/Compass#84]
Hi, 

Thank you so much for your excellent work! I have one issue with compass when running my bulk RNA-seq data. My input was normalized CPM and got many negative numbers. I have removed NA NaN NULL using R and python and double-checked manually. But still it crashed like this:

```
/data/msun/miniconda3/lib/python3.9/site-packages/pandas/core/arraylike.py:397:` RuntimeWarning: invalid value encountered in log2
  result = getattr(ufunc, method)(*inputs, **kwargs)
```

```
Traceback (most recent call last):
  File "/data/msun/miniconda3/bin/compass", line 8, in <module>
    sys.exit(entry())
  File "/data/msun/miniconda3/lib/python3.9/site-packages/compass/main.py", line 616, in entry
    runCompassParallel(args)
  File "/data/msun/miniconda3/lib/python3.9/site-packages/compass/main.py", line 651, in runCompassParallel
    for _ in pool.imap_unordered(partial_map_fun, range(n_samples)):
  File "/data/msun/miniconda3/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
Exception: CPLEX Error  1225: Numeric entry is not a double precision number (NaN).
```

Could you instruct me how to fix this?

**Comment by KunFang93** [comment]
Hi,

I met same issue. I wondered if you find a way to solve it. Thanks~

Best,
Kun

**Comment by zhengxy-april** [comment]
Hi,

I met same issue. I wondered if you find a way to solve it. Thanks~

Best
